name: luacheck

on: [push, pull_request]

jobs:
  luacheck:
    name: luacheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          sudo apt-get update      
          pip install poetry
          poetry install
      - name: Run Pytest
        run: poetry run pytest
